CREATE TABLE IF NOT EXISTS backtest_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_at TEXT NOT NULL,
    strategy_name TEXT NOT NULL,
    strategy_config TEXT NOT NULL,
    symbol TEXT NOT NULL,
    period_start TEXT,
    period_end TEXT,
    bars_processed INTEGER,
    runtime_ms INTEGER,
    total_trades INTEGER,
    wins INTEGER,
    losses INTEGER,
    win_rate_pct REAL,
    avg_win REAL,
    avg_loss REAL,
    profit_factor REAL,
    net_pnl REAL,
    total_return_pct REAL,
    cagr REAL,
    sharpe_ratio REAL,
    sortino_ratio REAL,
    max_drawdown_pct REAL,
    max_drawdown_duration_days INTEGER,
    volatility REAL,
    total_slippage_cost REAL,
    total_fees_cost REAL,
    avg_trade_duration_days INTEGER,
    equity_curve TEXT
);
